### ISSUE TITLE
Need some whitespaces?

### ISSUE THREAD

**Issue by Grief-Code** [FujiMakoto/IPS-Topic-Post-Stats#1]
https://github.com/FujiMakoto/IPS-Topic-Post-Stats/blob/master/hooks/postStatsLink.php#L39-L130

:hear_no_evil: 

I just have a small question, does this lines:
```
		$title = \IPS\Member::loggedIn()->language()->addToStack( 'userTopicStats_title' ) . ' - ' . $topic->mapped('title') . ' - ' . $forum->_title;
		\IPS\Output::i()->title = \IPS\Member::loggedIn()->language()->addToStack( $title );
```
extend the member class of IPS with new information? Im looking since days for that info now.

**Comment by FujiMakoto** [comment]
It just sets the title of the page. \IPS\Output contains all the output data sent to the client. You set \IPS\Output::i()->title to set the title, \IPS\Output::i()->jsFiles to set the loaded Javascript files, \IPS\Output::i()->output for the actual output template and so on.
